version: "3"
services:

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/notebooks"

  database-service:
    image: postgres:10
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=senhaBanco
      - POSTGRES_USER=postgres
      - POSTGRES_DB=escola
      - POSTGRES_DB_TEST=escola-test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
